// Copié de : https://github.com/DNUM-SocialGouv/1j1s-stage-orchestrateur-transform-load/blob/main/src/stages/transformation/domain/1jeune1solution/domaine.ts

export const domaineStage = [
	{ libellé: 'Achats', valeur: 'achats' },
	{ libellé: 'Activités Sociales et Culturelles', valeur: 'activités sociales et culturelles' },
	{ libellé: 'Agriculture', valeur: 'agriculture' },
	{ libellé: 'Architecture / urbanisme / Immobilier', valeur: 'architecture / urbanisme / immobilier' },
	{ libellé: 'Audit', valeur: 'audit' },
	{ libellé: 'Chimie / Biologie / Agronomie', valeur: 'chimie / biologie / agronomie' },
	{ libellé: 'Commerce', valeur: 'commerce' },
	{ libellé: 'Communication', valeur: 'communication' },
	{ libellé: 'Community Management', valeur: 'community management' },
	{ libellé: 'Comptabilité / Contrôle de Gestion', valeur: 'comptabilité / contrôle de gestion' },
	{ libellé: 'Conception / Génie civil / Génie industriel', valeur: 'conception / génie civil / génie industriel' },
	{ libellé: 'Conseil', valeur: 'conseil' },
	{ libellé: 'Design / UX / UI', valeur: 'design / UX / UI' },
	{ libellé: 'Développement Informatique', valeur: 'développement informatique' },
	{ libellé: 'Direction D\'entreprise', valeur: 'direction d\'entreprise' },
	{ libellé: 'Énergie / Matériaux / Mécanique / Électronique', valeur: 'énergie / matériaux / mécanique / électronique' },
	{ libellé: 'Enseignement', valeur: 'enseignement' },
	{ libellé: 'Environnement', valeur: 'environnement' },
	{ libellé: 'Évènementiel', valeur: 'évènementiel' },
	{ libellé: 'Études / Statistiques / Data', valeur: 'études / statistiques / data' },
	{ libellé: 'Fiscalité / finance / Assurance', valeur: 'fiscalite / finance / assurance' },
	{ libellé: 'Gestion de Projet / Produit', valeur: 'gestion de projet / produit' },
	{ libellé: 'Graphisme / Illustration', valeur: 'graphisme / illustration' },
	{ libellé: 'Infra / Réseaux / Télécoms', valeur: 'infra / réseaux / télécoms' },
	{ libellé: 'Hôtellerie - Restauration', valeur: 'hôtellerie - restauration' },
	{ libellé: 'Journalisme / Rp / Médias', valeur: 'journalisme / rp / médias' },
	{ libellé: 'Juridique', valeur: 'juridique' },
	{ libellé: 'Logistique', valeur: 'logistique' },
	{ libellé: 'Luxe / Mode / Textile', valeur: 'luxe / mode / textile' },
	{ libellé: 'Marketing', valeur: 'marketing' },
	{ libellé: 'Production / Fabrication / Exploitation', valeur: 'production / fabrication / exploitation' },
	{ libellé: 'Qualité / Maintenance', valeur: 'qualité / maintenance' },
	{ libellé: 'Rh / Formation', valeur: 'rh / formation' },
	{ libellé: 'Santé / Services à la Personne', valeur: 'santé / services à la personne' },
	{ libellé: 'Secteur Public', valeur: 'secteur public' },
	{ libellé: 'Relation Client / Support', valeur: 'relation client / support' },
	{ libellé: 'Travaux / Chantiers', valeur: 'travaux / chantiers' },
	{ libellé: 'Ventes', valeur: 'ventes' },
	{ libellé: 'Non Renseigné', valeur: 'non renseigné' },
];
