type PageGroup =
	'accueil'
	| 'accompagnement'
	| 'accompagnement_detail'
	| 'accompagnement_liste'
	| 'aides_logement'
	| 'apprentissage'
	| 'autres'
	| 'benevolat'
	| 'benevolat_detail'
	| 'benevolat_liste'
	| 'contenu_statique'
	| 'contrat_engagement_jeune'
	| 'cv'
	| 'decouvrir_les_metiers_detail'
	| 'decouvrir_les_metiers_liste'
	| 'deposer_offre_emploi'
	| 'deposer_offre_stage'
	| 'emplois'
	| 'engagement_entreprise'
	| 'entreprendre'
	| 'formation'
	| 'formation_apprentissage_liste'
	| 'formation_apprentissage_detail'
	| 'immersions'
	| 'je_deviens_mentor'
	| 'je_recrute'
	| 'je_recrute_afpr_poei'
	| 'job_ete'
	| 'job_etudiants'
	| 'job_europe'
	| 'logement'
	| 'logement_conseils'
	| 'mentorat'
	| 'mes_aides_financières'
	| 'mesures_employeurs_detail'
	| 'mesures_employeurs_liste'
	| 'metiers'
	| 'mon_espace'
	| 'métier'
	| 'page_404'
	| 'participer_a_un_evenement'
	| 'reference_entreprise'
	| 'service_civique'
	| 'service_civique_detail'
	| 'service_civique_liste'
	| 'service_jeune_liste'
	| 'stages';

export const SITE_TAGS: Record<string, string> = {
	site_entity: 'Min. Travail',
	site_environment: process.env.NEXT_PUBLIC_ANALYTICS_ENVIRONMENT || 'dev',
	site_target: 'information',
	site_type: 'multiple',
};

export interface PageTags {
	page_template: PageTemplate;
	pagegroup: PageGroup;
	pagelabel: PageLabel;
	'segment-site': SegmentSite;
}

type SegmentSite =
	'accueil'
	| 'autres'
	| 'contenu_detail'
	| 'contenu_liens'
	| 'contenu_liste'
	| 'funnel_etape_1'
	| 'funnel_etape_confirmation'
	| 'funnel_etape_intermediaire'
	| 'offres_d_emploi'
	| 'page_404'
	| 'page_de_base'
	| 'resultats_de_recherche';

type PageLabel =
	'accueil'
	| 'accompagnement'
	| 'aides_logement'
	| 'autres'
	| 'benevolat'
	| 'contenu_detail_niv_2'
	| 'contenu_liste_niv_1'
	| 'contenu_statique'
	| 'contrat_engagement_jeune'
	| 'cv'
	| 'deposer_offre_emploi_confirmation'
	| 'deposer_offre_emploi_etape_1'
	| 'deposer_offre_emploi_etape_intermediaire'
	| 'deposer_offre_stage_etape_1'
	| 'emplois'
	| 'emplois_detail'
	| 'emplois_liste'
	| 'engagement_entreprise'
	| 'engagement_entreprise_confirmation'
	| 'engagement_entreprise_etape_1'
	| 'engagement_entreprise_etape_intermediaire'
	| 'entreprendre'
	| 'formation'
	| 'immersions'
	| 'je_deviens_mentor'
	| 'je_recrute'
	| 'je_recrute_afpr_poei'
	| 'je_recrute_confirmation'
	| 'je_recrute_etape_1'
	| 'je_recrute_etape_intermediaire'
	| 'job_europe'
	| 'logement'
	| 'logement_conseils'
	| 'mentorat'
	| 'mes_aides_financières'
	| 'metiers'
	| 'mon_espace'
	| 'métier'
	| 'page_404'
	| 'participer_a_un_evenement'
	| 'reference_entreprise_confirmation'
	| 'reference_entreprise_etape_1'
	| 'reference_entreprise_etape_intermediaire'
	| 'service_civique';

type PageTemplate =
	'accueil'
	| 'accompagnement'
	| 'aides_logement'
	| 'autres'
	| 'benevolat'
	| 'contenu_detail_niv_2'
	| 'contenu_liste_niv_1'
	| 'contenu_statique'
	| 'contrat_engagement_jeune'
	| 'cv'
	| 'deposer_offre_emploi_confirmation'
	| 'deposer_offre_emploi_etape_1'
	| 'deposer_offre_emploi_etape_intermediaire'
	| 'deposer_offre_stage_etape_1'
	| 'emplois'
	| 'emplois_detail'
	| 'emplois_liste'
	| 'engagement_entreprise'
	| 'engagement_entreprise_confirmation'
	| 'engagement_entreprise_etape_1'
	| 'engagement_entreprise_etape_intermediaire'
	| 'entreprendre'
	| 'formation'
	| 'immersions'
	| 'je_deviens_mentor'
	| 'je_recrute'
	| 'je_recrute_afpr_poei'
	| 'je_recrute_confirmation'
	| 'je_recrute_etape_1'
	| 'je_recrute_etape_intermediaire'
	| 'job_europe'
	| 'logement'
	| 'logement_conseils'
	| 'mentorat'
	| 'mes_aides_financières'
	| 'metiers'
	| 'mon_espace'
	| 'métier'
	| 'page_404'
	| 'participer_a_un_evenement'
	| 'reference_entreprise_confirmation'
	| 'reference_entreprise_etape_1'
	| 'reference_entreprise_etape_intermediaire'
	| 'service_civique';
