enum SecteurActiviteDescription {
	ACCOMMODATION= 'Hébergement et restauration',
	ADMINISTRATIVE= 'Activités administratives et de soutien',
	AGRICULTURE= 'Agriculture, sylviculture et pêche',
	ARTS= 'Arts, spectacles et loisirs',
	CONSTRUCTION= 'Construction',
	EDUCATION= 'Éducation',
	ELECTRICITY= 'Production et distribution d‘électricité, de gaz, de vapeur et d‘air conditionné',
	EXTRATERRITORIAL= 'Activités des organisations et organismes extraterritoriaux',
	FINANCIAL= 'Activités financières et d‘assurance',
	HEALTH= 'Activités de santé humaine et d‘action sociale',
	HOUSEHOLDS= 'Activités des ménages en tant qu‘employeurs; activités indifférenciées de production de biens et de services pour usage propre des ménages',
	INFORMATION= 'Information et communication',
	MANUFACTURING= 'Industrie manufacturière',
	MINING= 'Extraction minière et exploitation en carrière',
	OTHER_SERVICES= 'Autres activités de services',
	PROFESSIONAL= 'Activités professionnelles, scientifiques et techniques',
	PUBLIC_ADMINISTRATION= 'Administration publique et défense; sécurité sociale obligatoire',
	REAL_ESTATE= 'Activités immobilières',
	RETAIL_TRADE= 'Commerce de gros et de détail; réparation de véhicules automobiles et de motocycles',
	TRANSPORT= 'Transport et entreposage',
	WATER_SUPPLY= 'Captage, traitement et distribution d‘eau; assainissement, gestion des déchets et dépollution',
};


export const secteurActiviteEures = [
	{ libellé: SecteurActiviteDescription.AGRICULTURE, valeur: 'A' },
	{ libellé: SecteurActiviteDescription.MINING, valeur: 'B' },
	{ libellé: SecteurActiviteDescription.MANUFACTURING, valeur: 'C' },
	{ libellé: SecteurActiviteDescription.ELECTRICITY, valeur: 'D' },
	{ libellé: SecteurActiviteDescription.WATER_SUPPLY, valeur: 'E' },
	{ libellé: SecteurActiviteDescription.CONSTRUCTION, valeur: 'F' },
	{ libellé: SecteurActiviteDescription.RETAIL_TRADE, valeur: 'G' },
	{ libellé: SecteurActiviteDescription.TRANSPORT, valeur: 'H' },
	{ libellé: SecteurActiviteDescription.ACCOMMODATION, valeur: 'I' },
	{ libellé: SecteurActiviteDescription.INFORMATION, valeur: 'J' },
	{ libellé: SecteurActiviteDescription.FINANCIAL, valeur: 'K' },
	{ libellé: SecteurActiviteDescription.REAL_ESTATE, valeur: 'L' },
	{ libellé: SecteurActiviteDescription.PROFESSIONAL, valeur: 'M' },
	{ libellé: SecteurActiviteDescription.ADMINISTRATIVE, valeur: 'N' },
	{ libellé: SecteurActiviteDescription.PUBLIC_ADMINISTRATION, valeur: 'O' },
	{ libellé: SecteurActiviteDescription.EDUCATION, valeur: 'P' },
	{ libellé: SecteurActiviteDescription.HEALTH, valeur: 'Q' },
	{ libellé: SecteurActiviteDescription.ARTS, valeur: 'R' },
	{ libellé: SecteurActiviteDescription.OTHER_SERVICES, valeur: 'S' },
	{ libellé: SecteurActiviteDescription.HOUSEHOLDS, valeur: 'T' },
	{ libellé: SecteurActiviteDescription.EXTRATERRITORIAL, valeur: 'U' },
];
