export enum ErreurMétier  {
  SERVICE_INDISPONIBLE = 'SERVICE_INDISPONIBLE',
  DEMANDE_INCORRECTE = 'DEMANDE_INCORRECTE',
  CONFLIT_D_IDENTIFIANT = 'CONFLIT_D_IDENTIFIANT',
  CONTENU_INDISPONIBLE = 'CONTENU_INDISPONIBLE',
}
