export enum ErrorType  {
  SERVICE_INDISPONIBLE = 'SERVICE_INDISPONIBLE',
  DEMANDE_INCORRECTE = 'DEMANDE_INCORRECTE',
  ERREUR_INATTENDUE = 'ERREUR_INATTENDUE',
  RESSOURCE_INTROUVABLE = 'RESSOURCE_INTROUVABLE',
  CONTENU_INDISPONIBLE = 'CONTENU_INDISPONIBLE',
}
