name: HTML5 Validator
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checks HTML5
        uses: Cyb3r-Jak3/html5validator-action@v0.4.1
        with:
          root: .next/server/pages/
          log_level: INFO
      - uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.log