name: Déploiement en Recette

# Déployer lors de chaque commit/merge sur la branche "main"
on:
  push:
    branches: [ main ]

jobs:
  recette:
    # uses: DNUM-SocialGouv/1j1s-front/.github/workflows/terraform.yml@main
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      apply: true
      environnement_name: scalingo-recette
      environnement_url: https://recette.1jeune1solution.gouv.fr
    # Avoid concurrency on the same terraform state
    concurrency: terraform-state-recette
